name: 'Solidity Unit Tests Action'
description: 'Runs unit testing on solidity contracts'
inputs:
  test-path:
    description: 'Path to file or directory containing all test files'
    required: true
  compiler-version:
    description: 'set compiler version (e.g: 0.6.1, 0.7.1 etc)'
  evm-version:
    description: 'set evm version (e.g: istanbul, berlin etc)'
    required: false
  optimize:
    description: 'set optimize (e.g: true, false)'
    required: false
    default: 'false'
  optimizer-runs:
    description: 'set optimizer runs (e.g: 200)'
    required: false
    default: '0'
  node-url:
    description: 'set node url (e.g: https://mainnet.infura.io/v3/your-api-key)'
    required: false
  block-number:
    description: 'set block number (e.g: 123456)'
    required: false
    default: 'latest'
  hard-fork:
    description: 'set hard fork (e.g: istanbul, berlin etc. See full list of hard forks here: https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common/src/hardforks)'
    required: false
  
outputs:
  time: # id of output
    description: 'The time the test suite ran'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'  
  color: 'green'
